### ISSUE TITLE
Cutting guide boxes extruded out from fitting surface of fibula cutting guide

### ISSUE THREAD

**Issue by SteveMaisi** [SlicerIGT/SlicerBoneReconstructionPlanner#60]
Hello. I'm having trouble with my fibula cutting guide because the cutting boxes are extruded from the guide's fitting surface (orange arrows). I've experienced this issue twice in past cases, and it's coming up again. It's not too bad because I can still trim it off after it's printed. Is there a way to fix this?

![image](https://user-images.githubusercontent.com/97390689/181677819-349c811b-4e77-4725-9d9c-e3d1d402f97b.png)

**Comment by mauigna06** [comment]
I think if I get working the adaptedMiterBoxes branch the problem you mention would be solved.

But I need to solve the issue first of allowing the user reverse the order of how the fibula pieces are created. That means: allow him that the first fibula piece is proximal and make it easy to achieve with a button

Please give me some time

**Comment by mauigna06** [comment]
> But I need to solve the issue first of allowing the user reverse the order of how the fibula pieces are created. That means: allow him that the first fibula piece is proximal and make it easy to achieve with a button

This was solved.

Please try the code of this branch:
https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/tree/AdaptedBiggerMiterBoxesV2

![adapterMiterBoxesScreenshot](https://user-images.githubusercontent.com/19158307/181910368-f8cd47e1-2926-43c0-958e-86658e020068.png)

@SteveMaisi the bottom of the boxes matches the fibula a bit more avoiding the orange arrow problems you mentioned

If there are a lot of successful plannings (i.e. good feedback) with this branch it may become part of the main branch

**Comment by SteveMaisi** [comment]
Hi Steve. The problem is that you missed a step in the segmentation instructions of the fibula:

5. Go to Wrap Solidify effect and click apply. (This is needed because it is recommended that bone segmentations have no holes inside so the assisted miterBox positioning algorithms work well)


To achieve correct miterBoxes positioning in your current plan: fix the fibula segmentation as explained above (do change the fibulaSegmentationSelector in BoneReconstructionPlanner to another segmentation and then point it back to the fibula segmentation so that the inputs update internally). Then click on "Create bone models from segmentations" and then you can click on "Create miter boxes from fibula planes" and it should work (see the attached picture).

Best Regards,

Mauro

**Comment by SteveMaisi** [comment]
Hi Mauro. Thank you for solving the problem, really appreciated it. Actually, I've been skipping the wrap solidify step because I noticed the segmented surface become rougher and dimensionally slightly altered. This is true when I 3D printed the models, both fibula and fibula cutting guide was no more a perfect fitting. I tried many settings however this is the most satisfactory result. I copy paste this problem and put in BRP issues. is that ok?

Before wrap solidification
![image](https://user-images.githubusercontent.com/97390689/192679519-c07c877b-4715-4e8e-ae99-793c1bccb2ab.png)

after warp solidification
![image](https://user-images.githubusercontent.com/97390689/192679595-f8c39dce-96f9-4f3a-8711-4b70f62ea94d.png)

the setting
![image](https://user-images.githubusercontent.com/97390689/192679644-995cbed7-9732-4f87-a936-55e000179fc4.png)

**Comment by SteveMaisi** [comment]
Hi Steve. 

It's a known problem that using wrap solidify changes the smoothing factor of all segments

Please look at the image in this link:
https://discourse.slicer.org/t/option-to-disable-smoothing-of-the-segment-surfaces-in-segment-editor/883/16?u=mau_igna_06

Please check that Smoothing factor is 0.50 (the default value of Slicer) and if not change it, that should solve some of fitting problem. 

Also have in mind that there is a feature missing to compensate guide-base fitting over bone with periosteum, that should solve the fitting problem completely

Mauro

**Comment by lassoan** [comment]
> It's a known problem that using wrap solidify changes the smoothing factor of all segments

@mauigna06 it should be very easy to fix this. We need to save the original smoothing factor and restore it in the end. Most likely just two lines of code. Would you have time to look at it? Or at least submit an issue to the SurfaceWrapSolidify extension repository to make sure we don't forget about to fix this? Thank you!

**Comment by mauigna06** [comment]
> > It's a known problem that using wrap solidify changes the smoothing factor of all segments
> 
> @mauigna06 it should be very easy to fix this. We need to save the original smoothing factor and restore it in the end. Most likely just two lines of code. Would you have time to look at it? Or at least submit an issue to the SurfaceWrapSolidify extension repository to make sure we don't forget about to fix this? Thank you!

Yes, I'll look into it

**Comment by mauigna06** [comment]
The problem stated at [the first comment of this issue](https://github.com/SlicerIGT/SlicerBoneReconstructionPlanner/issues/60#issue-1321717971) (bad positioning of miterBoxes):

> ![181677819-349c811b-4e77-4725-9d9c-e3d1d402f97b](https://user-images.githubusercontent.com/19158307/222925314-01d87473-c25f-427a-880e-ca8f131bed7f.png)

It's due to threshold segmentation of the fibula without applying wrapSolidify to fill cancellous bone which makes the boxes positioning algorithm don't work well.

There are two options: 
- Ask the user to input the fibula CT and mandible CT, and segment them fully (cortical bone + cancellous bone) through AI
- Improve the positioning algorithm to discard the inner cancellous bone polygon before continuing processing

**Comment by mauigna06** [comment]
- miterBoxes could be substracted with the fibula model, before joining them to the guidebase. This would achieve the best miterBox welding
